name: Deploy Flutter Web

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.6'  # Update to your Flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter web
        run: flutter build web --release

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/checkout@v2

      - name: Copy Flutter web build to the deployment directory
        run: cp -r build/web/* $GITHUB_WORKSPACE

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: $GITHUB_WORKSPACE
